name: Generate README
on: [push, pull_request, workflow_dispatch]
jobs:
  generate-readme:
    runs-on: ubuntu-latest
    permissions: { contents: write }
    steps:
      - uses: actions/checkout@master

      - uses: awalsh128/cache-apt-pkgs-action@latest
        with:
          packages: graphviz
          version: 1.0

      - uses: pnpm/action-setup@v4
        with:
          version: 10
          run_install: false

      - uses: actions/setup-node@v5
        with:
          node-version: "latest"
          cache: "pnpm"

      - run: pnpm install

      - run: npm run start output.svg

      - name: Commit output.svg
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: Generate output.svg"
          file_pattern: output.svg
